### ISSUE TITLE
CLI for 4.4: Report more feature properties

### ISSUE THREAD

**Issue by rickhelmus** [boecker-lab/sirius#1]
Hello,

I just noticed that 4.4 contains quite a few cool new functionalities! One of them is feature detection (lcms-align). I was wondering if more feature properties could be reported to facilitate further integration in _patRoon_. Nice to haves would be: peak intensity/height and area (which is reported currently?) and the retention time and m/z range for each feature.

Thanks,
Rick

**Comment by kaibioinfo** [comment]
Hi,

we currently report peak height, because it is more robust (in particular for MS2 heavy workflows, where we do not have high quality MS1). For future updates we plan to also store the mass traces of the features, such that all other properties can be easily calculated on the fly.

**Comment by mfleisch** [comment]
With 4.5.0 mass traces are now available on compound level in the project-space as gzipped json (`lcms.json.gz`).

**Comment by rickhelmus** [comment]
Awesome! Looking forward to try it!
