### ISSUE TITLE
Webservice drops

### ISSUE THREAD

**Issue by elnurgar** [boecker-lab/sirius#112]
Hello,

We have some problems with sirius on our server computer. The webservice drops sometimes. The problem is solved by checking if is unchecked or unchecking if checked of SSL Validation. Why can it happen? 

Thank you very much

**Comment by mfleisch** [comment]
Hey,
changing the ssl validation setting restarts complete the networking stack of SIRIUS.
So I guess it is not really related to the SSL setting at  but rather that changing the setting closes and deletes som faulty connections that seem for some reason not be able to reconnect.

* Have you observed some pattern when this happens?
* Can you please provide the logs when you observer the problem again.

**Comment by elnurgar** [comment]
Hi, here is the error:
APP_SERVER ERROR: 81 | Could not load version info (unsecured api endpoint). Bad Response Code.
Could not connect to the SIRIUS web service (REST API

**Comment by mfleisch** [comment]
We fixed quite a few issues here. Please reopen if problem still exists.
