### ISSUE TITLE
Webservice Connection unavaliable

### ISSUE THREAD

**Issue by kuntuse** [boecker-lab/sirius#116]
Hi,
This happened today when I was using it, which I have never encountered before.
Everything seems to be right, but can't work.
My sirius version is 5.6.3, ubuntuGUI.
Maybe I did something wrong. I hope you can tell me, thank you very much.
![image](https://user-images.githubusercontent.com/122350213/233958427-9ed4c06a-1b86-4b60-9b10-639319d5eccb.png)

**Comment by mfleisch** [comment]
This seemed to be a temporary issue. Please reopen if problem still exists.
