### ISSUE TITLE
Nothing is imported

### ISSUE THREAD

**Issue by MilouArts** [boecker-lab/sirius#126]
Hey!

I updated to Sirius to 5.8 from 5.7, I wanted to import the same mzmine sirius export file (.mgf) as I have done previously in 5.7 but nothing appears. I get a loading screen that its importing but no compounds appear on the left side. 
I am logged in with my academic licence.  

Thanks in advance. 

Milou

**Comment by mfleisch** [comment]
Hey can you please provide the file.

**Comment by MilouArts** [comment]
here is a wetransfer link to the file: https://we.tl/t-nh5S2hzA5D

**Comment by mfleisch** [comment]
Thanks for the data. Should be fixed in the latest update.
