### ISSUE TITLE
support for gzipped files

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#13]
Hi!

Wonderful work on Sirius 4.5.0!

I am used to working with mzML.gz files with my other pipelines without problems, would it be possible to support importing them gzipped?

Best,

**Comment by mfleisch** [comment]
Hey,
I think we cannot support gzipped mzml in a efficient manner. We are relying on jmzml for parsing mzml and do not want  to change this. Jmzml is using an index on the mzml file to efficiently access specific XML objects. 

Therefore we cannot pass a compressed Stream directly into the File parser. 

One thing we could do is extracting the compressed input in some temp directory before parsing. But I do not see how this improves anything compared to doing the same step beforehand on the command line.
Would that help anyhow?

**Comment by Adafede** [comment]
It is not a real issue...was only a question since many tools support it, your answer clarifies why it is not the case, and should not be a problem at all...just some Go to store :D

Thank you for your answer!

**Comment by mfleisch** [comment]
Ok, then we leave it "unfixed" for now.
