### ISSUE TITLE
sirius 4.8.2 --> sirius 5.8.3

### ISSUE THREAD

**Issue by oyileo** [boecker-lab/sirius#131]
Hi:
I use the following command in sirius 4.8.3：
`sirius --maxmz=850 -i ../03-S12_Sirius-removev2/S12.list_clean.mgf -o ./sirius-test formula -c 50 -p orbitrap zodiac fingerid -d BIO canopus`

but when I use the sam command in sirius 5.8.3, it prompt:
`Unmatched arguments from index 13: 'fingerid', '-d', 'BIO', 'canopus'`

so, how shold I use the same command in sirius 5.8.3?

**Comment by zmahnoor14** [comment]
Maybe it might work if you replace:
```
fingerid -d BIO canopus
```
with:
```
fingerprint structure --database bio canopus
```
OR
```
fingerprint structure --database bio compound-classes
```

**Comment by mfleisch** [comment]
@zmahnoor14 is right fingerprint prediction and structure db search have been split into separate tools.

Example commands are also available here:
https://boecker-lab.github.io/docs.sirius.github.io/cli/#csifingerid-predicting-molecular-fingerprints-compound-tool

Further `--help` gives you an overview over all available subtools. For each subtool a more specific help message can be printed with e.g. `fingerprint --help`
