### ISSUE TITLE
Error when storing custom db

### ISSUE THREAD

**Issue by Eli-Rousseau** [boecker-lab/sirius#138]
Good day everyone,

I am currently using the CLI of sirius 5.8.4. where I am trying to use the custom-db tool. 
Whenever I try to import my .tsv file with the following command:
```bash
sirius custom-db --import=database.tsv
```
I receive the following error message on my console:
```bash
SEVERE: error when storing custom db
```

When I try then to display the list of imported custom databases with this other command:
 ```bash
sirius custom-db --show
```
It indicates me the following:
 ```bash
==> No Custom database found!
```

I will provide you an additional screenshot as attachment. In any case, I very much look forward to your response, and hopefully you will be able to assist me.

Best regards,
Eli Rousseau.

![custom-db_error](https://github.com/boecker-lab/sirius/assets/133600052/f630b6c2-b611-4ae6-9da5-b978c5b01275)

**Comment by joXemMx** [comment]
Hi, looks to me like you are simply missing a login. Please make sure you are logged in before calling `custom-db` and see if the error remains.

**Comment by Eli-Rousseau** [comment]
Indeed I overlooked this detail, thanks for pointing it out. However, after successfully connecting to my account, I tried to use the custom-db tool with the same command as described in my last message:
 ```bash
sirius custom-db --import=database.tsv
```
And I still have the same error message:
 ```bash
SEVERE: error when storing custom db
```
But this time with a different exemption message (see below).

And when I try then to display the list of imported custom databases with this other command:
 ```bash
sirius custom-db --show
```
It indicates me the following:
 ```bash
==> No Custom database found!
```
Could you further help me out with this?

![error message 2](https://github.com/boecker-lab/sirius/assets/133600052/6211f17b-7222-4e6a-b3bf-939189a0dd0a)

**Comment by Hryflow** [comment]
The correct syntax is like:
Sirius -i trans-1.tsv custom-db --import=/full/path/to/myDB
1. while "-i" is indicate a global input, here is where you enter your tsv file. I put my file under SIRIUS main folder, i works well.
2. "--import=" indicate the database you want to create. The "--import" parameter expects a full path. As my test, SIRIUS gui can recognize it automaticlly.

**Comment by Eli-Rousseau** [comment]
Thank you very much for your contribution @Hryflow. I did manage to save my custom database this time. I had overlooked to use syntax with the ``-i`` option in my command. So my problem is solved and herewith I will close this issue.

Best regards,
Eli Rousseau.
