### ISSUE TITLE
minimal work to obtain a CANOPUS annotation

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#14]
Hi,

I would like to only compute compound classes for each of my spectra without the need for any molecular formula, structure, or whatever, what would be the shortest command line to do so? Is using an empty homemade DB an idea to go faster?

Best

**Comment by kaibioinfo** [comment]
You have to compute formula+fragmentation tree+fingerprint, as all those are necessary for compound class prediction. You can skip the structure database search, though.
However, it seems that selecting "none" in the database selection has no effect. I would consider this a bug.

Performance wise it does not make any difference, though. Structure database searching is the fastest part of the whole thing.

**Comment by Adafede** [comment]
Thanks, 

so would the following be ok in your opinion?

`sirius  -i <input> -o <output> F -c 1  --no-isotope-filter --no-isotope-score S C`

**Comment by kaibioinfo** [comment]
Getting the molecular formula right is crucial for compound class annotation. Ideally, you would use a larger number of formula candidates (10-50), using isotope pattern scoring and ZODIAC to enhance annotations on larger datasets.

**Comment by Adafede** [comment]
Thank you very much!

**Comment by mfleisch** [comment]
Seems to be resolved.
