### ISSUE TITLE
Can not find `v5.8.6/sirius-5.8.6-linux64-headless.zip`

### ISSUE THREAD

**Issue by JosieHong** [boecker-lab/sirius#148]
Hi, The link expired when I tried to install the headless version of Linux. May I get the valid link? Thanks!

**Comment by zglong1** [comment]
Seems like all of the headless version links have expired, I can't find them anywhere.

**Comment by joXemMx** [comment]
Hi @JosieHong and @zglong1, it is not the case that the links expired but rather that no headless versions were build and released in the last months. Meaning there is no 'valid' link. But you can always use the release including the GUI in CLI mode as well.

**Comment by JosieHong** [comment]
> Seems like all of the headless version links have expired, I can't find them anywhere.

Hi @zglong1, I found that we could install the GUI and CLI version and run it as `sirius asService`, then it works on the machine without a monitor.
