### ISSUE TITLE
4.5.0 does not run from Linux/R

### ISSUE THREAD

**Issue by rickhelmus** [boecker-lab/sirius#15]
Hi guys,

Something strange is going on with the new 4.5.0 release on Linux when I try to run it from `R`.

When the `sirius` binary is executed, all kinds of Java options are prepended to the command line arguments, which obviously make the command fail. Example output:

```
> system2("/home/rick/Rproj/deps/sirius/bin/sirius", "-i")
INFO  15:45:40 - Sirius Workspace Successfull initialized at: /home/rick/.sirius-4.5
INFO  15:45:40 - You run SIRIUS 4.5.0
INFO  15:45:40 - Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v8.1.0, CPLEX-v12.7.1, COIN-OR-v1.17.3
INFO  15:45:40 - Treebuilder priorities are: [CLP, CPLEX, GUROBI, GLPK]
INFO  15:45:40 - CPU check done. 4 cores that handle 8 threads were found.
INFO  15:45:40 - Bug reporter initialized.
INFO  15:45:41 - Web API initialized.
INFO  15:45:41 - Running with following arguments: [-Djava.library.path=/home/rick/Rproj/deps/sirius/lib/app:/home/rick/Rproj/deps/sirius/bin, -Djava.launcher.path=/home/rick/Rproj/deps/sirius/bin, -Xms1G, -XX:MaxRAMPercentage=85, --illegal-access=permit, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, -Djava.library.path=/home/rick/Rproj/deps/sirius/lib/app/../native, -javaagent:/home/rick/Rproj/deps/sirius/lib/app/agents-4.4.8.jar, -classpath, /home/rick/Rproj/deps/sirius/lib/app/sirius_cli-4.5.0.jar:/home/rick/Rproj/deps/sirius/lib/app/cdk-structgen-2.3.jar:/home/rick/Rproj/deps/sirius/lib/app/woodstox-core-5.0.3.jar:/home/rick/Rproj/deps/sirius/lib/app/cdk-fragment-2.3.jar:/home/rick/Rproj/deps/sirius/lib/app/cdk-cip-2.3.jar:/home/rick/Rproj/deps/sirius/lib/app/commons-configuration2-2.4.jar:/home/rick/Rproj/deps/sirius/lib/app/jakarta.xml.bind-api-2.3.3.jar:/home/rick/Rproj/deps/sirius/lib/app/GraphUtils-1.1.jar:/home/rick/Rproj/deps/sirius/lib/app/animal-sniffer-annotations-1.18.jar:/home/rick/Rproj/deps/sirius/lib/app/maven-artifact-3.5.0.jar:/home/rick/Rproj/deps/sirius/lib/app/jnati-deploy-0.4.jar:....
```
(output truncated).

When running from the shell no problems occur though. The problem can be reproduced with the `patRoon` docker image: https://hub.docker.com/r/patroonorg/patroonrs

If you need more details please let me know!

Thanks,
Rick

**Comment by mfleisch** [comment]
Hey, 
this is indeed strange. Maybe some character escaping issue when running from R or within docker. I will have a look.

**Comment by mfleisch** [comment]
I can reproduce the issue.

**Comment by mfleisch** [comment]
I am not sure if I can find out why the binary is not working with R since it is produced by the jpackage tool of the JDK. 
Python and other languages I have tested are working fine.

As a quick fix you can simply bypass the binary and run java directly: 

The command would be: 

`system2('/home/rick/Rproj/deps/sirius/lib/runtime/bin/java', args = c('-Xms1G', '-XX:MaxRAMPercentage=85', '--illegal-access=permit', '--add-opens', 'java.base/java.lang=ALL-UNNAMED', '--add-opens', 'java.base/java.net=ALL-UNNAMED', '-Djava.library.path=/home/rick/Rproj/deps/sirius/lib/native', '-javaagent:/home/rick/Rproj/deps/sirius/lib/app/agents-4.4.8.jar', '-cp', '"/home/rick/Rproj/deps/sirius/lib/app/*"', 'de.unijena.bioinf.ms.frontend.SiriusGUIApplication' , '-V'))`

I used `-V` exemplary for the parameters of SIRIUS.

We can include a bash script launcher that is going to do the same in upcoming versions.

**Comment by rickhelmus** [comment]
Hi Markus,

Many thanks for the quick replies! For now I added a small `sh` script to `patRoon` based on your last comment. Note that it uses `SiriusCLIApplication` instead of `SiriusGUIApplication`, took me some time to realize why headless wasn't working ;-) This also seems to work for the GUI release package.

```sh
#!/bin/sh
SIRBINPATH="$1"
JAVAPATH="$SIRBINPATH/../lib/runtime/bin/java"
LIBPATH="$SIRBINPATH/../lib"

shift

"$JAVAPATH" -Xms1G -XX:MaxRAMPercentage=85 --illegal-access=permit --add-opens java.base/java.lang=ALL-UNNAMED \
    --add-opens java.base/java.net=ALL-UNNAMED -Djava.library.path="$LIBPATH/native" \
    "-javaagent:$LIBPATH/app/agents-4.4.8.jar" -cp "$LIBPATH/app/*" \
    de.unijena.bioinf.ms.frontend.SiriusCLIApplication $@
```
The first shell argument should be the path to the `bin` directory. The other arguments are directly passed to `SIRIUS`.

**Comment by mfleisch** [comment]
Version 4.5.1 now contains a shell script for Linux that should work with R.

@rickhelmus The java command has slightly changed, so you might have to adopt to the included script.
