### ISSUE TITLE
[lcms align]

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#16]
Hi,

Me again, testing all the wonderful possibilities you offer!

<del>I ran the LCMS-align on a **single** file and it gave me files containing info about peak shape and isotopic pattern quality as output. 
When running it on multiple files however this information gets (or at least I guess so...) lost. Wouldn't it be possible to get a list of them among samples? (for example, peak shape good for sample 1, bad for sample 2, etc.) </del>

**EDIT**: It comes from the F command...strangely, if you start a F command you have the info, else not, is this wanted?

Just having a quick look at it also seems to indicate that some "noise" is taken into account as features. (as it looks that there is no parameter available could it be that default options detect redundant "features" having absolutely no peak shape?)

I attach a screenshot where you can see an example of problematic ion being detected 324 times as "feature", where 1-2 times, in the beginning, could be ok but it is along with the whole chromatogram sadly.

<img width="1792" alt="Capture d’écran 2020-11-25 à 08 56 22" src="https://user-images.githubusercontent.com/44283913/100199188-2490b900-2efd-11eb-9f31-29aa239bf4b3.png">

Thanks a lot again and congrats on all the great tools!

**Comment by kaibioinfo** [comment]
Hi,
we only store very general quality information about the merged spectrum. For individual samples the information can be recalculated easily. So we might rather add a REST command for that.

Regarding the peak picking: 324 times sounds way too much. But in general we look for each individual MS/MS as a single feature and merge or split two features if their MS/MS is similar or dissimilar. If your instrument shot 324 MS/MS in for this m/z and they all are very different (can totally happen if their quality is low and they are dominated by noise peaks) then it ends up with 324 individual features. Usually, we filter out features with low quality MS/MS in the end. I don't know why this did not happened here.

I also experimented with several peak shape filters (like: as more peaks you detect within a single m/z mass trace, as larger their apex has to be to be identified as individual peak), but always got the feeling that the very simple filters (like simple peak smoothing) are similar effective.

**Comment by kaibioinfo** [comment]
One more thing: There are a lot of good quality MS/MS belonging to really low quality peak shapes (like no shape at all). This often happens when people do untargeted analysis with few MS and too many MS/MS scans. That's why I always rather look at the quality of the MS/MS than the quality of the peak shape.

**Comment by Adafede** [comment]
Thanks a lot for your detailed answer!

I completely agree with the comment on peak shape, and yes this 324 times is extreme but I think a nice example of the "at the limit" case. 
I am just wondering...you do not mention any rt limit for merging ms/ms scans, is it the case?

Of course, it does not apply to the specific problem since the ion will pop up all over the chromatogram, so I do not expect it to be merged in a single feature. (thanks btw, now I will add it to the exclusion list :D)

maybe filtering out features that come too often, on an almost regular rt? From my human perspective they are similar, here a short example of 3 out of 324:

```
BEGIN IONS
FEATURE_ID=9438
PEPMASS=186.07612482706705
MSLEVEL=2
CHARGE=1
SCANS=9438
RTINSECONDS=1613.483
55.93511199951172 67593.5107421875
85.02881774396845 817423.8515625
90.94808197021484 26508.060546875
113.96370697021484 32437.46875
114.05491996537619 326843.80078125
123.94561767578125 20394.09765625
126.0549322367161 85254.83447265625
146.96107482910156 21253.458984375
181.9508232628287 56848.3662109375
186.0762317550644 114141.71484375
END IONS

BEGIN IONS
FEATURE_ID=9439
PEPMASS=186.07611519949776
MSLEVEL=2
CHARGE=1
SCANS=9439
RTINSECONDS=1616.366
85.02885437011719 117765.1640625
114.05496215820312 41872.3046875
126.05548858642578 10505.158203125
186.07676696777344 16630.396484375
END IONS

BEGIN IONS
FEATURE_ID=9440
PEPMASS=186.07612991333008
MSLEVEL=2
CHARGE=1
SCANS=9440
RTINSECONDS=1617.719
55.935125072973086 64367.3359375
85.02881253160376 926024.125
114.05497741699219 381289.0
126.05500338985394 95124.8671875
128.95103454589844 8961.8828125
163.94004821777344 7303.2529296875
181.95035849588797 27491.9833984375
186.07593462470638 122926.572265625
END IONS
```
