### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Kingphen001** [boecker-lab/sirius#20]
I'm so sorry to bother you，how should I download Sirius 4.5, it seems that there is a small problem that cannot be downloaded.

Best,
Kingphen

**Comment by Kingphen001** [comment]
SIRIUS+CSI:FingerID GUI and CLI - Version 4.5.1 (2020-11-24)

**Comment by kaibioinfo** [comment]
Hi,
our build server / artifactory crashed today. As soon as it is up again, download links should work again.

**Comment by Kingphen001** [comment]
Thanks for your swift reply!  Sirius is a powerful tool for mass spectrometry.

**Comment by kaibioinfo** [comment]
Downloads should work again.
