### ISSUE TITLE
Error when loading confidence SVMs 

### ISSUE THREAD

**Issue by nirshahaf** [boecker-lab/sirius#22]
Hello and happy new year,

When running from command line with the following settings:

_"sirius -i [input] -o [output] --recompute --ignore-formula formula --ppm-max-ms2=15 -e='CHNOPSCl[3]Br[2]Na' --candidates=10 --ilp-solver='GUROBI' structure --database pubchem canopus"_

I keep getting these warnings - do they relate to an upcoming feature that needs some specific setup?

"Error when loading confidence SVMs or the bayesian network. Confidence SCore will not be available!"

**Comment by mfleisch** [comment]
Hey,
thanks and a happy new year for you too. 

The confidence score models for the bayes net scoring we recently integrated are not ready yet and are therefore missing on the server side. SIRIUS is already prepared for the confidence score and will be able to compute confidence scores as soon as the new models are are available.

**Comment by nirshahaf** [comment]
Thanks, I guess I'll have to keep updating versions :-!
