### ISSUE TITLE
Trees

### ISSUE THREAD

**Issue by nirshahaf** [boecker-lab/sirius#24]
Apologies for opening 2021 with so many Issues...

A previous Sirius version had the option (now apparently cancelled) to generate fragmentation tree in the .dot format, which could then be rather easily converted to figures via a third party app. 
However current version generates only .json files. Can you perhaps add to the documentation an outline of a procedure from .json  tree files to a graphical tree representation (as was previously outlines for the .dot files)?

**Comment by mfleisch** [comment]
The graphical user interface of SIRIUS offers tree export as `svg`,`pdf`,`dot` and `json` format.
You can open an already computed project and export the trees you want as vector graphics or dot.  
![treeExport](https://user-images.githubusercontent.com/11212267/103492064-c07ce100-4e28-11eb-8092-0f3e2fecc6b4.png)

**Comment by nirshahaf** [comment]
The GUI is super nice, but could you perhaps list the internal functions (or library dependencies) which produce the tree? 
I would like to generate a batch procedure for this task, if possible.

**Comment by mfleisch** [comment]
We add the tree export as `json` and `dot` as standalone tool to the CLI. A new build including this features will be available in the next days.

**Comment by nirshahaf** [comment]
Hi Markus,

Fair enough, but in this case I think it's also necessary to merge back the missing documentation explaining how to convert using 'GraphViz'. In version manual 4.0.1 it's found under the headline 'Visualizing fragmentation trees'.

Thanks!

**Comment by mfleisch** [comment]
Dot file export now available in [SIRIUS](https://bio.informatik.uni-jena.de/software/sirius/) 4.6.0 via the [`ftree-export`](https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/#fragmentation-tree-export-tool) tool.
The documentation has also been updated regarding dot export and conversion.
