### ISSUE TITLE
Training structures for negative icon mode

### ISSUE THREAD

**Issue by pwpgomes** [boecker-lab/sirius#3]
Doesn't version 4.4 (Beta) have negative files?

**Comment by mfleisch** [comment]
The models for negative predictions are not finished.
CSI:FingerID models are coming soon. Negative CANOPUS prediction may take some more time.

**Comment by pwpgomes** [comment]
Ok. Does this prevent me from importing my spectra in negative mode into Sirius 4.4?
I am having difficulties, since in version 4.0.1 there is the option "batch import". In this version 4.4 I cannot load my spectrums. 
How do I do?

**Comment by kaibioinfo** [comment]
What is the file format of your data?

**Comment by pwpgomes** [comment]
MGF format, DDA experiments.

**Comment by kaibioinfo** [comment]
Just put all spectra of the same compound into the same file. When you import them, they should be imported as a single compound.

You can also put all spectra of all compounds into a single file. Consecutive spectra with different PEPMASS are splitted into separate compounds.

See example file:

[example.mgf.txt](https://github.com/boecker-lab/sirius/files/4541486/example.mgf.txt)

**Comment by pwpgomes** [comment]
Ok, thanks. 
Another doubt. There is a forecast to complete the training in negative mode via CSI:Finder

**Comment by kaibioinfo** [comment]
We are currently working on it. Might be today or tomorrow.

**Comment by mfleisch** [comment]
CSI:FingerID for negative ion mode data is now available for the SIRIUS 4.4 beta (since 4.4.16-SNAPSHOT).
