### ISSUE TITLE
Specifying enforced elements in .ms file

### ISSUE THREAD

**Issue by pleeferguson** [boecker-lab/sirius#31]
Hi, I would like to run the Sirius CLI in batch mode so that I can avoid having to call a new JVM for every formula calculation I am doing, but I need to be able to set different enforced elements for each individual spectrum input.  I cannot seem to make this work within the .ms file format.  I can of course use the `-E` flag within the CLI arguments, but then the same elemental alphabet will be applied across all calculations.  However, when I specify `>elements `within the .ms files, the elemental alphabet seems to be treated analogous to the CLI argument `-e` (elements considered).

Perhaps I'm missing a feature?  Please let me know if this is possible or if it could be implemented.

**Comment by kaibioinfo** [comment]
Hi Lee,

you can specify the enforced elements with
`>FormulaSettings.enforced C,H,N,O,P,S,Cl,Br,I`

In fact, you can set all kind of config options this way. A list of all available config options can be found in <home>/.sirius-4.7/custom.config

**Comment by mfleisch** [comment]
Just for completion:
```shell
sirius config -h
```
should give you the list of possible parameters from the command line.
