### ISSUE TITLE
Result ".csv"s are actually .tsv

### ISSUE THREAD

**Issue by wkumler** [boecker-lab/sirius#4]
Hi! I've recently started using SIRIUS via CLI and have been super impressed with its functionality. 

One thing that has been causing me some issues, however, is that all the exported .csv files are actually separated by tabs ( \t character). Since I'm using SIRIUS as part of a larger workflow, I'm going through and renaming them after the fact so that I can open them properly in other programs (e.g. Excel). Would it be possible to modify the file extension while they're being written out so this doesn't need to happen as a separate step afterwards?

As far as I can tell, literally just changing the file extension from ".csv" to ".tsv" resolves the problem and gives the user a heads-up about the file format without breaking any of the later workflow.

**Comment by kaibioinfo** [comment]
Hi,
csv means "character separated values", so the ending is technically correct, it is Excel which is wrong. 

However, you are not the first one complaining about the file ending, so we REALLY should do something about it (I know myself how difficult it is to open these files in excel under windows).

**Comment by wkumler** [comment]
Huh, okay. I've never heard of the .csv ending standing for "character separated values". I've always assumed that it meant the character delimiter is specifically a comma, and it does seem like Excel (and [R](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/read.table), and [Python](https://docs.python.org/3/library/csv.html), and the [IETF](https://tools.ietf.org/html/rfc4180.html)) expects that format when parsing files with the .csv ending.

**Comment by mfleisch** [comment]
I think the most valuable solution would be to just let the user choose the file extension of the summary files. Fefault would still be `csv` a command line parameter would allow to change it. This would help to be compatible with e.g.  the excel `csv` exporter and will not break existing workflows that are using the `.csv` extension. Since SIRIUS does never read the summary files this should also not make much trouble on our side.

**Comment by kaibioinfo** [comment]
> I think the most valuable solution would be to just let the user choose the file extension of the summary files.
I don't see any advantage. Let us just use .tsv and update the scripts which depend on the filename.

> and it does seem like Excel (and R, and Python, and the IETF) expects that format when parsing files with the .csv ending.
Basically every application let you choose the delimiter (python, R and so on are using comma by default for convenience, but you can use your own). Excel is rather an exception.

I totally see your point and it does not hurt to change the file ending. We just have to be careful that other applications (like GNPS) that rely on the file names are updated.

**Comment by mfleisch** [comment]
fixed with build 4.4.18

**Comment by lfnothias** [comment]
Thanks @kaibioinfo, I noted the changes and will update workflows accordingly
