### ISSUE TITLE
Error in Linux executable vs MacOS executable

### ISSUE THREAD

**Issue by eeko-kon** [boecker-lab/sirius#48]
Hello!

I am using sirius exec both in my iOS and a linux machine with the same exact parameters but from an OpenMS wrapper (SiriusAdapter) with the following command:
`
 SiriusAdapter -executable resources/Sirius/sirius/bin/sirius -in results/20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3/interim/sirius/PCfeature_nch_20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3.mzML -in_featureinfo results/20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3/interim/sirius/MFD_nch_20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3.featureXML -out_sirius results/20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3/interim/sirius/formulas_20210827_UMETAB219_POS_FPY12_Plate-2_MDNAWGS18_rep3.mzTab -preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+" -sirius:elements_enforced CHN[15]OS[4] -project:processors 2 -debug 3 `

which basically corresponds to:

`
sirius -in "path/to/temp.ms" -out "path/to/output.txt"  preprocessing:filter_by_num_masstraces 2 -preprocessing:feature_only -sirius:profile orbitrap -sirius:db none -sirius:ions_considered "[M+H]+, [M-H2O+H]+, [M+Na]+, [M+NH4]+" -sirius:elements_enforced CHN[15]OS[4] -project:processors 2 -debug 3 `

I have several very complex files, some of which include a high number of high mass compounds (compound timeout is by default set to 100s) - for those files, it seems that sirius in macOS runs (completes the run in e.g. 57min) but in my linux system it produces the following error:

```
SEVERE  09:20:16 - <83601>[SiriusSubToolJob | 353_20211208_085100_metabotest2_99880_2__2162765726596644275-2509--2508--UNKNOWN@630m/z] ToolChain Job failed due to: java.lang.NullPointerException: Cannot invoke "de.unijena.bioinf.ChemistryBase.ms.ft.FTree.getTreeWeight()" because "solve.tree" is null
WARNING 09:22:11 - <83951>[SiriusSubToolJob | 445_20211208_085100_metabotest2_99880_2__7001155623839493666-2824--2823--UNKNOWN@1393m/z] ToolChain Job canceled due to: de.unijena.bioinf.jjobs.exceptions.TimeoutException: Timeout reached!
```

p.s. I am using Sirius 4.9.9 headless

Thank you in advance!
Efi

**Comment by eeko-kon** [comment]
solved with new release somehow

**Comment by mapio** [comment]
I have the same issue (a NullPointerException) in version 5.5.7.

Have you closed the issue because you've found a fix? In case, what was it?
