### ISSUE TITLE
[Feature request] Add canopus_npc export

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#49]
Hi guys,

Would be nice to have the 
```
from canopus import Canopus
C = Canopus(sirius="sirius_projectspace")
C.npcSummary().to_csv("npc_summary.csv")
```
from [Kai's repo](https://github.com/kaibioinfo/canopus_treemap) directly integrated into SIRIUS, maybe as an optional argument...

Hope this makes sense, thank you for all your work!

**Comment by mfleisch** [comment]
SIRIUS 5 will contain an exporter tool that provides a similar output:

`sirius -i <my-project> export-predictions --npc -o <prediction.tsv>`
