### ISSUE TITLE
Instability of CSI:FingerID Server

### ISSUE THREAD

**Issue by Rommelio-coli** [boecker-lab/sirius#51]
Hello everyone!
I want to share sometimes I experience connection instability with CSI:FingerID server when I try to run it in SIRIUS 4.9.9
It would be very interesting to know if anyone else is going through the same.
Thanks beforehand!

**Comment by louwenjjr** [comment]
Yes I'm having the same problem! Sirius is printing out:
```
WARNING 11:25:03 - Error when try to connect to Server. Try again in 120.0s
 Cause: Error when querying REST service. Bad Response Code: 414 | Message: Request-URI Too Long| Content: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Long</title>
</head><body>
<h1>Request-URI Too Long</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at rp1.mirz.uni-jena.de Port 443</address>
</body></html>
```

**Comment by mfleisch** [comment]
@louwenjjr which SIRIUS version are you using?

**Comment by mfleisch** [comment]
`414 Request-URI Too Long` has been fixed some time ago. just gorgot close the issue.
