### ISSUE TITLE
CHARGE error

### ISSUE THREAD

**Issue by yellow-byte** [boecker-lab/sirius#54]
Hi, when exporting MS/MS mgf files using MZmine in negative ion mode, the precursor ions of some features are determined to be CHARGE=0. Incredibly, this could potentially be re-determined in SIRIUS as [M+?] +, why is this? Also, it is possible that a similar phenomenon occurs in the positive ion mode.
A solution is urgently needed and much appreciated.

**Comment by mfleisch** [comment]
If no charge is given in the input SIRIUS tries to guess it from the file and feature name (searches for strings like `neg` or `negative`). If this also fails, the default is `[M+?] +` which stands for _unknown positive_  .
However, SIRIUS 5 (coming soon) will allow you to change the adduct/ionization for multiple feature/compounds at once using the GUI.
