### ISSUE TITLE
How to set the adduct ion type to [2M+H] or [2M-H]?

### ISSUE THREAD

**Issue by CUCOCC** [boecker-lab/sirius#55]
How to set the adduct ion type to [2M+H] or [2M-H]?
I am very confused about this question.
Hope you can give answers.
Thank you very much.

**Comment by mfleisch** [comment]
Hey, Multimers are not yet supported by SIRIUS.
See, https://boecker-lab.github.io/docs.sirius.github.io/faq/#could-sirius-support-for-multimeres

**Comment by CUCOCC** [comment]
> Hey, Multimers are not yet supported by SIRIUS. See, https://boecker-lab.github.io/docs.sirius.github.io/faq/#could-sirius-support-for-multimeres

That's really a pity.
But SIRIUS is a very good software.
Thank you so much!
