### ISSUE TITLE
Negative ionization mode interpretation in Sirius MS format

### ISSUE THREAD

**Issue by AharoniLab** [boecker-lab/sirius#57]
Hi. I see a possible bug in the reading/interpretation of MS files with unknown adduct in the negative ionization mode. E.g. for the following input:

_
>compound 100008992 (1-stearoyl-2-docosahexaenoyl-GPE)
>parentmass 790.5395
>ionization **[M-?]-**
>instrumentation Waters QTOF-HRMS

>ms1
790.5405827917 523.65971971618
791.544290518561 273.425397221785
792.551573367295 52.3557014903044

>ms2
165.0403 14242.8135
239.0586 2731.761
239.2387 142.4587
253.2161 2793.1611
269.2481 18269.2871
270.2509 1593.8157
etc.
_

Sirius-4.9.5-win64 CLI automatically generates the following .ms file:
_
>compound 100008992 (1-stearoyl-2-docosahexaenoyl-GPE)
>parentmass 790.5395
>ionization **[M]-**
>instrumentation Q-ToF (LCMS)
>source [local path the original .ms file]
>quality UNKNOWN

>ms1peaks
790.5405827917 523.65971971618
791.544290518561 273.425397221785
792.551573367295 52.3557014903044

>ms2peaks
etc.
_

By converting the adduct from unknown to a naturally deprotonated ion, Sirius creates a downstream error in neutral formula calculation which further results in missing or wrong CSI-FID annotation etc. By manually fixing the [M]- to [M-H]- I could restore the correct formula and further get some nice annotations by CSI and CANOPUS. However as I see that this is a reoccurring pattern for all [M+?]- tags, which does not happen in the positive mode - where [M+?]+ tags remain as such - I think there is sufficient reason to open a bug report.

**Comment by marcus-ludwig** [comment]
Hi,

the generic unknown negative ionization is  specified as `[M+?]-` in SIRIUS. If you use `[M-?]-` this will be incorrectly recognized and parsed to `[M]-`. But `[M+?]-` should work fine.

Best,
Marcus
