### ISSUE TITLE
sirius-5.4.0-SNAPSHOT-osx64.pkg: does not start on macOS Monterey

### ISSUE THREAD

**Issue by mlocardpaulet** [boecker-lab/sirius#61]
Hello,

I have downloaded sirius-5.4.0-SNAPSHOT-osx64.pkg and ran the install. 
SIRIUS starts and stops/shuts down without starting the GUI.
See attached log with system description. I work with a macOS Monterey, it may be the issue.
Happy to provide more information if needed.

[Install_issues.txt](https://github.com/boecker-lab/sirius/files/8311651/Install_issues.txt)

**Comment by mfleisch** [comment]
Thank for reporting (in particular for the log).
Seems to be a native library problem with the JAVA runtime. I will have a look and gat back to you asap.

Have you used SIRIUS 4 before? Did SIRIUS 4 work on macOS Monterey?

**Comment by mfleisch** [comment]
Hey,
the macOS Monterey bug should be fixed with version 5.4.1-SNAPSHOT.

Please confirm if it works now.
