### ISSUE TITLE
Problem exporting Alligned feature list gap-filled filtered (MZMine2) for SIRIUS

### ISSUE THREAD

**Issue by Jsanzmoxo** [boecker-lab/sirius#63]
Hello SIRIUS team, 

recently I have been running some MZMines to export the data for SIRIUS identifications and the following error message appears:

Joined features have different polarity. This is most likely a bug. If not, please separate them as individual features and/or write a feature request on github.

This only happens when i´m working with LC-MS/MS data with low resolution. Any help you can give me a I would appreaciate a lot.

Thank you in advance.

**Comment by kaibioinfo** [comment]
Does this error message occurs in SIRIUS or in MZMine? I don't find this kind of error message in the SIRIUS code. Just from the text I would say you have mixed spectra, positive and negative mode, within one file which is not supported in SIRIUS.

**Comment by kaibioinfo** [comment]
Please open a ticket in https://github.com/mzmine/mzmine2 as we cannot do anything on the SIRIUS side to fix the issue.
