### ISSUE TITLE
[Feature request] Make `Command`available to copy-paste

### ISSUE THREAD

**Issue by Adafede** [boecker-lab/sirius#65]
Hi again!

A small detail that would probably help many users like me:

Could you make the text shown by the `Show Command` in the GUI available to copy/paste?

I think many command line arguments in Sirius 5.4.1 changed so having to rewrite it manually is a real pain 😢

**Comment by mfleisch** [comment]
Hey,
it should already be possible to highlight the command (e.g. with CTRL + A) and copy it with (CTRL + C). 
However, I opened a ticket to add a button with this functionality to the GUI.
