### ISSUE TITLE
Zodiac job crashing

### ISSUE THREAD

**Issue by titodamiani** [boecker-lab/sirius#66]
Hi,
I am testing the new [5.4.1 pre-release](https://github.com/boecker-lab/sirius/releases/tag/v5.4.1-SNAPSHOT) (CLI version for Linux) and running the following command on a feature list (MGF file) from MZmine 3:
`sirius5 -i <input_directory> -o <output_directory> --maxmz=800 --cores 16 formula zodiac fingerprint structure canopus`

It seems the `formula` tool runs smoothly, but it crashes when trying to run `zodiac`. I have two concerns in particular:

1. I get the following error message for the `formula` computation of some features:
`WARNING 18:45:42 - Could not load GrbSolver! Sirius was compiled with the following ILP solvers: GLPK-v1.7.0 (included), Gurobi-v9.1.1, CPLEX-v12.7.1, COIN-OR-v1.17.3: gurobi/GRBException`
However I didn’t specify any particular ILP solver. What is the error related to?

2. I get the following error when trying to run `zodiac`: 
`INFO    06:34:36 - START ZODIAC JOB`
`INFO    06:34:40 - TREES LOADED.`
`INFO    06:34:41 - Cluster enabled? false`
`INFO    06:34:41 - RUN ZsiriusODIAC`
`SEVERE  08:22:23 - <62375815>[EdgeCalculationWorker-62375815] Failed!`
`java.lang.Exception: java.lang.OutOfMemoryError: Java heap space`
`…`

Is it really a memory problem? Is there something I can change in the `zodiac` settings, or I just need more memory to make it work?

I uploaded data, script and log file (timsTOF.e10979044) here: https://drive.google.com/drive/folders/1eDXk-6Dh-mPzNUQmTgBvZJ4sZn0h-5UN?usp=sharing.

Thanks!

**Comment by marcus-ludwig** [comment]
Hi Tito,

1. there is a default order of ILP solvers that SIRIUS is trying to use. Gurobi is usually first. If it is not installed/found, SIRIUS will try to use the 2nd, and so on. Hence, this warning only tells you that SIRIUS is using the next solver (CPLEX or GLPK). This order can be changed via the GUI or in the sirus.properties file.
2. This is really a memory problem. ZODIAC has to keep the whole dataset in memory and also computes pairwise similarities between compounds. You have ~30000 compounds - that's is quite a lot. You can try reducing memory consumption by changing zodiac parameters. By default, ZODIAC try to enforce connections of each compound to the network, but that uses more memory. Running `zodiac --minLocalConnections 0 --edge-threshold 0.995` will lower memory consumption, but formula annotation may be worse for some compounds. For more, see https://boecker-lab.github.io/docs.sirius.github.io/cli/#zodiac-improve-molecular-formula-identifications. If you in the end sort the structure hits by COSMIC confidence score and only look at the best ones anyways, you may also consider skipping ZODIAC. You results may be a little worse but the confidence score helps you to prioritize the good annotations anyways.

Best,
Marcus

(feel free to reopen if you have further questions.)
