### ISSUE TITLE
Question about using ClusteredMGF extracted from GNPS jobs

### ISSUE THREAD

**Issue by Rommelio-coli** [boecker-lab/sirius#70]
Is it valid to use the ClusteredMGF extracted from a GNPS job as input for SIRIUS? I know it doesn't have the isotope pattern information but it still gives annotations and I got no issues when running the program.

If you need any extra information I´ll send it to you as quickly as I can.

**Comment by mfleisch** [comment]
Hey,
in principle this is valid and will work as intended. However you just need to be aware that the molecular formula identification cannot benefit from the isotope pattern score without isotope information which lowers the identification rate.
