### ISSUE TITLE
Question about LC-MS batch alignment in SIRIUS 4.9.15

### ISSUE THREAD

**Issue by Rommelio-coli** [boecker-lab/sirius#72]
Hi
I'm interested in processing multiple .mzXML files in a SIRIUS run. When I align, analyze and export these files, I get an FBMN quantification table with an ID, m/z, and RT. Where does the consensus RT come from for every peak? I know, first, the algorithm aligns MS/MS and then searches for precursor ions masses and retention times, no information about RT consensus calculation is available. It would be of great help if you could share this information. 

I really appreciate any help you can provide.

**Comment by kaibioinfo** [comment]
Hi,
current implementation is using the robust average (removing the 25% of the datapoints with lowest RT and 25% of the datapoints with the highest RT and calculate the average across the remaining ones). But that's something we might improve/change in future.
