### ISSUE TITLE
External server is down!

### ISSUE THREAD

**Issue by eeko-kon** [boecker-lab/sirius#75]
FYI :) - CSI cannot run (as a result)

**Comment by mfleisch** [comment]
Is it still the still the case for you?

**Comment by mfleisch** [comment]
Are you probably using some old SIRIUS version?
Can you please send the output of the log window.

**Comment by eeko-kon** [comment]
That was 5.4.1 version

<img width="1287" alt="Screenshot 2022-05-25 at 22 19 26" src="https://user-images.githubusercontent.com/54527247/170360195-bae4be95-b4a5-41fa-ac16-ca8bc311bae0.png">

<img width="1107" alt="Screenshot 2022-05-25 at 22 19 48" src="https://user-images.githubusercontent.com/54527247/170360206-6c065732-3dd0-4c03-8ef3-3c0246f993a0.png">

**Comment by mfleisch** [comment]
Hey,
5.4.1 was a pre-release. For pre-releases we do not provide any transition time regarding web service availability. It might be unavailable as soon as a newer version is released. Upgrading to the latest release (currently 5.5.3) should solve the issue.

FYI: A pre-release can be identified by its `pre-release` flag on the github releases page and the version number ends with  `-SNAPSHOT`

**Comment by eeko-kon** [comment]
Ahh I see. Thanks a lot! It also happened that some jobs from my CLI also failed so i thought that was related. I will double check and delete the GUI 5.4.1
