### ISSUE TITLE
conda install -c bioconda sirius-csifingerid

### ISSUE THREAD

**Issue by eeko-kon** [boecker-lab/sirius#77]
Could you please update the Sirius version for conda if possible? :) (In case things are faster in the new version...)

**Comment by mfleisch** [comment]
As we have discussed per email, we are currently waiting for review at conda-forge
https://github.com/conda-forge/staged-recipes/pull/16235

**Comment by mfleisch** [comment]
The  conda-forge package is available now:
https://github.com/conda-forge/sirius-ms-feedstock
