### ISSUE TITLE
Usage of custom database

### ISSUE THREAD

**Issue by JB-MS** [boecker-lab/sirius#8]
Hi there,

I have been recently using SIRIUS using a custom database using the import function of SMILES formulas. In the latest version, I have been looking for the possibility to define a custom database without success. Is this function still implemented and, if yes, where can I find it?

Thanks and Cheers,
Johannes

**Comment by mfleisch** [comment]
Hey Johannes, 
currently creating custom databases is not possible from the GUI but we are working on it an it will be available soon.

However, for now you can create the custom database using the command line tool. The created db will also be available in the GUI.

Best
Markus

**Comment by JB-MS** [comment]
Hi Markus,

thanks for the reply.  I will try out the CLI to create a db.

Cheers,
Johannes

**Comment by JB-MS** [comment]
Hi Markus,

 I am not sure how to define the input file for the custom-db. I have a .txt file with SMILES formulas in each line. In the CLI help for custom-db all other parameters are quite self-explaining, besides how to define the formulas or file(s) with formulas which should be incorporated into the custom db. Thanks!

Cheers,
Johannes

**Comment by mfleisch** [comment]
Hey Johannes,
The file can to contain tab separated columns `SMILES    ID     NAME`. But only the SMILES column is mandatory. So your file with one SMILES each line should be perfectly fine.

```
CN1CCCC1C2=C[N+](=CC=C2)[O-]	id-01	Caffein
CN1C=NC2=C1C(=O)N(C(=O)N2C)C	id-03	Nicotin
```

To ensure that the DB is visible in the GUI you must not use an output path (`--output`) for the custom-db. Just specify a name.
The DB will then be saved in the .sirius-4.4 config directory and automatically picked up when starting the GUI.

**Comment by JB-MS** [comment]
Hi Markus,

thanks for the quick reply! Sorry, I just realised that I put my question not fully clear. How can I define the input file option for the CLI command, i.e. what is the name of the option (I have tried `--input='SMILES.txt' `and `--db='SMILES.txt'`)? 

Cheers,
Johannes

**Comment by mfleisch** [comment]
Ah, got it! :-)
Due to the pipeline like structure of the SIRIUS command line tool input values are usually given with the global `-i,--input` parameter.

`sirius -i <INPUT_PATH> custom-db --name <DB_NAME>`

**Comment by JB-MS** [comment]
Hi Markus,

thanks for your help, it works fine now. 

Is the name given in the custom database used later on in the results, e.g. in the mzTab file? So far I could only find the link/id ref to the custom database. Or is there a way to enforce the usage of that name for the result files if the formula and structure matches the spectrum?

Cheers,
Johannes

**Comment by mfleisch** [comment]
Hey Johannes,
with 4.5.0 custom databases can now also be created from the GUI.
Further we fixed several issues with the output of database flags/links. Custom dbs should now be correctly exported with all the other database links.
