### ISSUE TITLE
SIRIUS 5 fails to open in Manjaro Linux

### ISSUE THREAD

**Issue by Dmente92** [boecker-lab/sirius#80]
I was using an older version of SIRIUS 4 and everything ran fine, but after updating to SIRIUS 5 it always fails to open with the following error:
Error: LinkageError occurred while loading main class de.unijena.bioinf.ms.frontend.SiriusCLIApplication
	java.lang.UnsatisfiedLinkError: /home/yami/sirius/lib/runtime/lib/libnio.so: /home/yami/sirius/lib/runtime/lib/libnio.so: undefined symbol: ipv6_available

**Comment by f-kretschmer** [comment]
Hi,
could you check if adding the `server` directory of the sirius java-runtime to the `LD_LIBRARY_PATH` helps?
So:
```bash
export LD_LIBRARY_PATH=/home/yami/sirius/lib/runtime/lib/server/:$LD_LIBRARY_PATH
./sirius gui
```
On arch-linx, this solves the problem.

**Comment by Dmente92** [comment]
> 

That solved the problem. Thank you!!!!
