### ISSUE TITLE
Linux GUI binary missing 

### ISSUE THREAD

**Issue by rwst** [boecker-lab/sirius#82]
Hello, both `sirius-5.5.7-linux64-headless.zip` and `sirius-5.5.7-linux64.zip` are missing a gui binary. Is this intended?

**Comment by mfleisch** [comment]
Hey, the GUI functionality is part of the  `sirius` Startscript. If you download a GUI version and run it without Parameters the GUI will start. Alternatively you can run `sirius gui`.

On Windows an additional `sirius-gui.exe` exists because windows destinguishes between GUI and CLI binaries.

**Comment by rwst** [comment]
OK, thanks. I failed to clean up a previous CLI installation.
