### ISSUE TITLE
Is it possible to use [M]+ as a possible adduct in SIRIUS?

### ISSUE THREAD

**Issue by pbjarterot** [boecker-lab/sirius#83]
Like the title says, I am using a database for derivatized metabolites, and my molecules are thus already charged by a positively charged nitrogen on the derivatizing matrix. So I would like to use [M]+ ionization for SIRIUS but have not found a way to do it manually, is this possible or would you need to make an updated version of the software?

**Comment by kaibioinfo** [comment]
Intrinsical charges always give us headache... Our current solution is to mostly ignore them. You can choose [M]+ as ionization (should be also in the UI), it will internally be treated like an [M+H]+, thus the displayed molecular formula might look wrong. For the database search, however, it should consider the charged compounds, too.

**Comment by mfleisch** [comment]
related/duplicate to #41
