### ISSUE TITLE
structure database search command line selecting 'all' databases: no fingerprints generated

### ISSUE THREAD

**Issue by helenamrusso** [boecker-lab/sirius#92]
Hi,
I am using Sirius 5.6.1. in the command line, and I have been experiencing an issue with the structure database step. When I select to search in **all**, no fingerprints are generated. I can see that the files structure_candidates.tsv in each folder are generated by containing only the headers. As a result, no compound_identifications_adducts.tsv or compound_identifications.tsv is generated with the write-summaries command.

When I don't specify as 'all', it works correctly. If I specify it as PubChem, or a full list of all of the databases, it also works. 
All the generated results, and the input sirius.mgf file can be found here: https://drive.google.com/file/d/1zhmSjBQPXegnsIEFUppIs7hOoyj_alDH/view?usp=sharing

Here are all the commands I ran for all the tests performed:

- **test_data_all:** compound_identifications_adducts.tsv or compound_identifications.tsv; structure_candidates.tsv empty.
/Users/helenarusso/Desktop/sirius_5_6_1.app/Contents/MacOS/sirius -i '/Users/helenarusso/Downloads/Test_data_Qemistree/sirius.mgf' -o '/Users/helenarusso/Downloads/Test_data_Qemistree/test_data_all' formula --profile orbitrap --database all --candidates 50 --ions-considered '[M+H]+' --tree-timeout 1600 --ppm-max 10 zodiac --thresholdFilter 0.98 fingerprint structure --database all canopus write-summaries

- **test_data_not_specified:** all works correctly.
/Users/helenarusso/Desktop/sirius_5_6_1.app/Contents/MacOS/sirius -i '/Users/helenarusso/Downloads/Test_data_Qemistree/sirius.mgf' -o '/Users/helenarusso/Downloads/Test_data_Qemistree/test_data_not_specified' formula --profile orbitrap --database all --candidates 50 --ions-considered '[M+H]+' --tree-timeout 1600 --ppm-max 10 zodiac --thresholdFilter 0.98 fingerprint structure canopus write-summaries

- **test_data_all_written:** all works correctly.
/Users/helenarusso/Desktop/sirius_5_6_1.app/Contents/MacOS/sirius -i '/Users/helenarusso/Downloads/Test_data_Qemistree/sirius.mgf' -o '/Users/helenarusso/Downloads/Test_data_Qemistree/test_data_all_written' formula --profile orbitrap --database all --candidates 50 --ions-considered '[M+H]+' --tree-timeout 1600 --ppm-max 10 zodiac --thresholdFilter 0.98 fingerprint structure --database BIO,PUBCHEM,MESH,HMDB,KNAPSACK,CHEBI,PUBMED,KEGG,HSDB,MACONDA,METACYC,GNPS,ZINCBIO,UNDP,YMDB,PLANTCYC,NORMAN,ADDITIONAL,PUBCHEMANNOTATIONBIO,PUBCHEMANNOTATIONDRUG,PUBCHEMANNOTATIONSAFETYANDTOXIC,PUBCHEMANNOTATIONFOOD,KEGGMINE,ECOCYCMINE,YMDBMINE canopus write-summaries

- **test_data_pubchem:** all works correctly.
/Users/helenarusso/Desktop/sirius_5_6_1.app/Contents/MacOS/sirius -i '/Users/helenarusso/Downloads/Test_data_Qemistree/sirius.mgf' -o '/Users/helenarusso/Downloads/Test_data_Qemistree/test_data_pubchem' formula --profile orbitrap --database all --candidates 50 --ions-considered '[M+H]+' --tree-timeout 1600 --ppm-max 10 zodiac --thresholdFilter 0.98 fingerprint structure --database pubchem canopus write-summaries

I also take the opportunity to highlight that it seems there is a discrepancy in your **structure --help** description.
  _-d, --db, --database=<dbName>[,<dbName>...]
                  Search structure in the union of the given databases. If no
                    database is given '**ALL**' internal databases are used.
                  Example: possible DBs: 'ALL,BIO,PUBCHEM,MESH,HMDB,KNAPSACK,
                    CHEBI,PUBMED,KEGG,HSDB,MACONDA,METACYC,GNPS,ZINCBIO,UNDP,
                    YMDB,PLANTCYC,NORMAN,ADDITIONAL,PUBCHEMANNOTATIONBIO,
                    PUBCHEMANNOTATIONDRUG,PUBCHEMANNOTATIONSAFETYANDTOXIC,
                    PUBCHEMANNOTATIONFOOD,KEGGMINE,ECOCYCMINE,YMDBMINE'
                  Default: **BIO**_

In the description it is mentioned that it should search in **ALL**, however, the default is **BIO**.

Thanks,
Helena

**Comment by mfleisch** [comment]
Hey @helenamrusso,
thanks for the detailed bug report. Both issues should be fixed in the upcoming release v5.6.3
