### ISSUE TITLE
Could not load a valid TreeBuilder (ILP solvers), tried ‘[CLP, GUROBI, CPLEX]’. Please read the installation instructions

### ISSUE THREAD

**Issue by Rommelio-coli** [boecker-lab/sirius#94]
Hallo, SIRIUS team.

I tried to analyze an .mgf generated through MZmine 2.53 (SIRIUS format) in the GUI of SIRIUS 5.6.2. After tuning parameters and tried to run, the next message appeared: "Could not load a valid TreeBuilder (ILP solvers), tried ‘[CLP, GUROBI, CPLEX]’. Please read the installation instructions" and couldn't run the analysis.

I hope you can aid me with this and, if this happens to others, it can help them too.

Thanks in advance and I'll wait patiently for your answer.

**Comment by mfleisch** [comment]
Which operating System are your using?

**Comment by mfleisch** [comment]
SIRIUS 5.6.4+  handles ILP solver dependency differently and might solve this issue. Further our new conda-forge package ([sirius-ms](https://anaconda.org/conda-forge/sirius-ms)) might also be worth trying to workaround these kind of problems. 

Closed, due to missing information to reproduce.
