### ISSUE TITLE
SIRIUS4 Server Connection Issue

### ISSUE THREAD

**Issue by li-chin** [boecker-lab/sirius#98]
Dear SIRIUS developer,

Hi, I have difficulties connecting to the server [SIRIUS versions used: 4.9.12 and 4.9.15] for a few days, for both gui and cli.

These are the error messages I received:

![image](https://user-images.githubusercontent.com/96451969/213076901-c06d007b-0e4c-41c3-aab9-42705310190c.png)
![image](https://user-images.githubusercontent.com/96451969/213077237-6cab538f-be8c-4689-ad6f-2b07b6fddcc3.png)
![image](https://user-images.githubusercontent.com/96451969/213077581-513d4bf2-467c-4d82-957c-42812e4b90d6.png)

May I check if there is a maintenance going on?

Thank you!

**Comment by joXemMx** [comment]
Hello, 

you encounter these issues because SIRIUS 4 web services have been shut down at the end of 2022 (see https://bio.informatik.uni-jena.de/2022/11/sirius-4-end-of-life/). Please switch to any version of SIRIUS 5 to continue using SIRIUS.

Best,
Jonas
